<?php
/**
 * @file
 * Drupal needs this blank file.
 */
function luggage_ct_node_view_alter(&$build) {
  if(strpos($_GET['q'], 'search/', 0) !== false) {
    $build['field_content_type'] = array(
      '#markup' => '<div class="content-type-indicator ' . $build['#bundle'] . '" title="' . ucfirst($build['#bundle']) . '">' . ucfirst(substr($build['#bundle'], 0, 2)) . '</div>',
      '#weight' => 0
    );
  } else if(strpos($_GET['q'], 'node/', 0) !== false) {

  }
}

function luggage_ct_block_view_alter(&$data, $block) {
  if($block->delta == 'GiIy4zr9Gu0ZSa0bumw1Y9qIIpIDf1wu' && $data != NULL) {
    foreach($data['content']['bundle']['#items'] as &$item) {
      $name = strtolower(get_string_between($item['data'], '>', ' ('));
      if($name == 'basic page') {
        $name = 'page';
      }
      $item['data'] = '<div class="content-type-indicator ' . $name . '">' . ucfirst(substr($name, 0, 2)) . '</div>' . $item['data'];
    }
    drupal_add_css(drupal_get_path('module', 'luggage_ct') . '/css/luggage_ct.css');
  }
}

function get_string_between($string, $start, $end){
  $string = " ".$string;
  $ini = strpos($string,$start);
  if ($ini == 0) return "";
  $ini += strlen($start);
  $len = strpos($string,$end,$ini) - $ini;
  return substr($string,$ini,$len);
}