<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_update_projects_alter().
 */
function luggage_indicator_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['luggage_indicator']);
}

function luggage_indicator_node_view_alter(&$build) {
  if(arg(0) == 'search') {
    $build['field_content_type'] = array(
      '#markup' => _get_identifier_element(node_type_get_name($build['#node']), 'ct-search', true),
      '#weight' => 0
    );
    _add_stylesheet();
  } else if(arg(0) == 'node') {
    $build['field_content_type_indicator'] = array(
      '#title' => 'Content Type Indicator',
      '#label_display' => 'none',
      0 => array(
        '#markup' => _get_identifier_element(node_type_get_name($build['#node']), 'ct-node', true)
      )
    );
    _add_stylesheet();
  }
}

function _add_stylesheet() {
  drupal_add_css(drupal_get_path('module', 'luggage_indicator') . '/css/luggage_indicator.css');
}

/**
 * @param $name - The name of the content type
 * @param $type - The type of the element (e.g. 'ct-node')
 * @param $title - If a tooltip should be shown
 * @return string - Returns a stringed html element
 */
function _get_identifier_element($name, $type, $title) {
  if($name == 'Biblio') {
    $name = 'Publication';
  }
  $str = '<div class="content-type-indicator ct-' . $name . ' '. $type;

  if($title) {
    $str = $str . '" title="' . ucfirst($name) . ' content type';
  }

  $str = $str . '">';

  if($type == 'block') {
    $str = $str . ucfirst(substr($name, 0, 2)) . '</div>';
  } else {
    $str = $str . ucfirst($name) . '</div>';
  }

  return $str;
}