<?php
/**
 * @file
 * Drupal needs this blank file.
 */
function luggage_indicator_node_view_alter(&$build) {
  if(arg(0) == 'search') {
    $build['field_content_type'] = array(
      '#markup' => _get_identifier_element($build['#bundle'], 'search', true),
      '#weight' => 0
    );
    _add_stylesheet();
  } else if(arg(0) == 'node') {
    $build['field_content_type_indicator'] = array(
      '#title' => 'Content Type Indicator',
      '#label_display' => 'none',
      0 => array(
        '#markup' => _get_identifier_element($build['#bundle'], 'node', true)
      )
    );
    _add_stylesheet();
  }
}

function luggage_indicator_block_view_alter(&$data, $block) {
  if($block->delta == 'GiIy4zr9Gu0ZSa0bumw1Y9qIIpIDf1wu' && $data != NULL) {
    foreach($data['content']['bundle']['#items'] as &$item) {
      $name = strtolower(_get_string_between($item['data'], '>', ' ('));
      if($name == 'basic page') {
        $name = 'page';
      } else if($name == '') {
        $inter = explode('>', $item['data']);
        $name = array_pop($inter);
      }
      $item['data'] = _get_identifier_element(trim($name), 'block', false) . $item['data'];
    }
    _add_stylesheet();
  }
}

function _add_stylesheet() {
  drupal_add_css(drupal_get_path('module', 'luggage_indicator') . '/css/luggage_indicator.css');
}

function _get_identifier_element($name, $type, $title) {
  if($name == 'biblio') $name = 'publication';

  $str = '<div class="content-type-indicator ct-' . lcfirst($name) . ' '. $type;

  if($title) {
    $str = $str . '" title="' . ucfirst($name) . ' content type';
  }

  $str = $str . '">';

  if($type == 'block') {
    $str = $str . ucfirst(substr($name, 0, 2)) . '</div>';
  } else {
    $str = $str . ucfirst($name) . '</div>';
  }

  return $str;
}

function _get_string_between($string, $start, $end){
  $string = " ".$string;
  $ini = strpos($string,$start);
  if ($ini == 0) return "";
  $ini += strlen($start);
  $len = strpos($string,$end,$ini) - $ini;
  return substr($string,$ini,$len);
}